#######################################################
# DO NOT EDIT THIS FILE!                              #
#                                                     #
# It's auto-generated by symfony-cmf/dev-kit package. #
#######################################################

############################################################################
# This file is part of the Symfony CMF package.                            #
#                                                                          #
# (c) 2011-2017 Symfony CMF                                                #
#                                                                          #
# For the full copyright and license information, please view the LICENSE  #
# file that was distributed with this source code.                         #
############################################################################

TESTING_SCRIPTS_DIR=vendor/symfony-cmf/testing/bin
CONSOLE=${TESTING_SCRIPTS_DIR}/console
ifneq (${BRANCH},"")
	VERSION=dev-${BRANCH}
else
	VERSION=dev-master
endif
PACKAGE=seo-bundle

list:
	@echo 'test:                    will run all tests'
	@echo 'test_unit:               will run unit tests only'
	@echo 'test_integration_phpcr:  will run integration tests on PHPCR'
	@echo 'test_integration_orm:    will run integration tests on ORM'

test: test_unit test_integration_phpcr test_integration_orm
